name: Void Build APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v3

      - name: 📢 Notify: Start
        run: |
          curl -X POST https://TU-DOMINIO.ngrok-free.dev/projects/webhook/build-finished \
          -H "Content-Type: application/json" \
          -d "{\"projectId\": \"b3aff62d-9ba0-4746-89a1-8a6a268decb6\", \"status\": \"STARTING\", \"downloadUrl\": \"PENDING\"}"

      - name: 🟢 Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ☕️ Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🚀 Setup Expo + EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📢 Notify: Installing
        run: |
          curl -X POST https://TU-DOMINIO.ngrok-free.dev/projects/webhook/build-finished \
          -H "Content-Type: application/json" \
          -d "{\"projectId\": \"b3aff62d-9ba0-4746-89a1-8a6a268decb6\", \"status\": \"INSTALLING\", \"downloadUrl\": \"PENDING\"}"

      - name: 📦 Install dependencies
        run: npm install --legacy-peer-deps

      - name: 📢 Notify: Building APK
        run: |
          curl -X POST https://TU-DOMINIO.ngrok-free.dev/projects/webhook/build-finished \
          -H "Content-Type: application/json" \
          -d "{\"projectId\": \"b3aff62d-9ba0-4746-89a1-8a6a268decb6\", \"status\": \"BUILDING_APK\", \"downloadUrl\": \"PENDING\"}"

      - name: 🏗 Build APK
        run: npx eas-cli build -p android --profile preview --local --non-interactive --output=app-release.apk

      - name: 📦 Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          name: Void Build v${{ github.run_number }}
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📢 Notify: Success
        run: |
          curl -X POST https://TU-DOMINIO.ngrok-free.dev/projects/webhook/build-finished \
          -H "Content-Type: application/json" \
          -d "{\"projectId\": \"b3aff62d-9ba0-4746-89a1-8a6a268decb6\", \"status\": \"SUCCESS\", \"downloadUrl\": \"https://github.com/FYSPA/Shop/releases/download/build-${{ github.run_number }}/app-release.apk\"}"