name: "Void Flash Sync"
on:
  workflow_dispatch:
    inputs:
      voidBuildId: { required: true }
      voidShortId: { required: true }
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Void Terminal Bridge"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          function v_log() {
            local type=$1
            while IFS= read -r line; do
              echo "[$type] $line"
              CLEAN=$(echo "$line" | tr -d '"' | tr -d "\\")
              curl -s -X POST https://nontheosophic-katherin-clumsiest.ngrok-free.dev/projects/webhook/logs \
                -H "Content-Type: application/json" \
                -H "ngrok-skip-browser-warning: true" \
                -d "{\"shortId\": \"${{ github.event.inputs.voidShortId }}\", \"message\": \"$CLEAN\", \"type\": \"$type\"}"
            done
          }

          echo "⚡️ Iniciando Flash Sync (OTA)..." | v_log github
          
          echo "📦 Preparando bundle de JavaScript..." | v_log github
          npm install --legacy-peer-deps 2>&1 | v_log github
          
          echo "🚀 Publicando actualización en Expo..." | v_log expo
          EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} npx eas-cli update --branch preview --message "VoidSync" --non-interactive 2>&1 | v_log expo

      - name: "Finish"
        if: always()
        run: |
          curl -s -X POST https://nontheosophic-katherin-clumsiest.ngrok-free.dev/projects/webhook/build-finished \
          -H "Content-Type: application/json" \
          -H "ngrok-skip-browser-warning: true" \
          -d "{\"projectId\": \"09e1e899-dc3d-456c-b3ab-63641c98ed07\", \"voidBuildId\": \"${{ github.event.inputs.voidBuildId }}\", \"status\": \"${{ job.status }}\", \"downloadUrl\": \"OTA\"}"