name: "Void Build APK"
on:
  workflow_dispatch:
    inputs:
      voidBuildId:
        description: "ID de la base de datos"
        required: true
      voidShortId:
        description: "ID corto"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Log: Start"
        run: |
          curl -X POST https://nontheosophic-katherin-clumsiest.ngrok-free.dev/projects/webhook/build-finished/logs -H "Content-Type: application/json" -d '{"shortId": "${{ github.event.inputs.voidShortId }}", "message": "Void ha tomado el control del servidor..."}'

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "Setup Expo"
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: "Log: Install"
        run: |
          curl -X POST https://nontheosophic-katherin-clumsiest.ngrok-free.dev/projects/webhook/build-finished/logs -H "Content-Type: application/json" -d '{"shortId": "${{ github.event.inputs.voidShortId }}", "message": "Instalando librerías y dependencias..."}'

      - name: "Install"
        run: npm install --legacy-peer-deps

      - name: "Log: Build"
        run: |
          curl -X POST https://nontheosophic-katherin-clumsiest.ngrok-free.dev/projects/webhook/build-finished/logs -H "Content-Type: application/json" -d '{"shortId": "${{ github.event.inputs.voidShortId }}", "message": "Iniciando compilación nativa de Android (Gradle). Esto tardará unos minutos..."}'

      - name: "Build"
        run: npx eas-cli build -p android --profile preview --local --non-interactive --output=app-release.apk

      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Notify Success"
        run: |
          curl -X POST https://nontheosophic-katherin-clumsiest.ngrok-free.dev/projects/webhook/build-finished/build-finished -H "Content-Type: application/json" \
          -d '{"projectId": "09e1e899-dc3d-456c-b3ab-63641c98ed07", "voidBuildId": "${{ github.event.inputs.voidBuildId }}", "status": "SUCCESS", "downloadUrl": "https://github.com/FYSPA/Shop/releases/download/build-${{ github.run_number }}/app-release.apk"}'